### ISSUE TITLE
Authorization Scope Adjustable

### ISSUE THREAD

**Issue by PeterMerkert** [ChrisAlvares/node-adwords#30]
In the readme, it says the scope for authorization is adjustable in this SDK. However, in the source code, I cannot see a possibility to change the scope without modifying the source: https://github.com/ChrisAlvares/node-adwords/blob/master/adwords/auth.js

Do I miss something?

**Comment by ChrisAlvares** [comment]
Hey Peter, 

You might have mis-read the documentation. To make it easy for people to use without much knowledge, we hardcoded the scope.

You can always use the https://github.com/google/google-api-nodejs-client to retrieve the refresh token and plug that into this library if you need extra scopes.

It might work out better that way since you are going to use that library to work with the other apis anyways.
